CREATE DATABASE TITANIC

USE TITANIC

SELECT * FROM TITANIC_DATASET;

BEGIN TRANSACTION;

-- data cleaning

-- count null value in each column
SELECT
	COUNT(CASE WHEN PassengerId IS NULL THEN 1 END) AS Passengerld,
	COUNT(CASE WHEN Survived IS NULL THEN 1 END) AS Survived,
	COUNT(CASE WHEN Pclass IS NULL THEN 1 END) AS Pclass,
	COUNT(CASE WHEN Name IS NULL THEN 1 END) AS Name,
	COUNT(CASE WHEN Sex IS NULL THEN 1 END) AS Sex,
	COUNT(CASE WHEN Age IS NULL THEN 1 END) AS Age,
	COUNT(CASE WHEN SibSp IS NULL THEN 1 END) AS SibSp,
	COUNT(CASE WHEN Parch IS NULL THEN 1 END) AS Parch,
	COUNT(CASE WHEN Ticket IS NULL THEN 1 END) AS Ticket,
	COUNT(CASE WHEN Fare IS NULL THEN 1 END) AS Fare,
	COUNT(CASE WHEN Cabin IS NULL THEN 1 END) AS Cabin,
	COUNT(CASE WHEN Embarked IS NULL THEN 1 END) AS Embarked
FROM TITANIC_DATASET;


-- Duplicate Name

SELECT
	Name,
	Count(Name) AS Dup_Name
FROM TITANIC_DATASET
GROUP BY Name
HAVING Count(Name)>1;


SELECT
	Ticket,
	Count(Ticket) AS Dup_Name
FROM TITANIC_DATASET
GROUP BY Ticket
HAVING Count(Ticket)>1;


-- EXTRA SPACES

SELECT
	LEN(Name) LEN_NAME,
	LEN(Name) - LEN(TRIM(Name)) LEN_SPACE_NAME
FROM TITANIC_DATASET
WHERE LEN(Name) - LEN(TRIM(Name))>0


SELECT
	LEN(Sex) LEN_SEX,
	LEN(Sex) - LEN(TRIM(Sex)) LEN_SPACE_SEX
FROM TITANIC_DATASET
WHERE LEN(Sex) - LEN(TRIM(Sex))>1


-- HANDLING NULL VALUES

-- AGE

UPDATE TITANIC_DATASET
SET Age = (SELECT AVG(Age) FROM TITANIC_DATASET)
WHERE AGE IS NULL;


UPDATE TITANIC_DATASET
SET Cabin = 'Not Defined'
WHERE Cabin IS NULL;

UPDATE TITANIC_DATASET
SET Embarked = 'Not Defined'
WHERE Embarked IS NULL;


-- INSIGHTS

-- TOTAL NUMBER OF PASSENGER
SELECT
	COUNT(PassengerId) AS TOTAL
FROM TITANIC_DATASET


-- TOTAL NUMBER OF SURVIVED AND UNSURVIVED PASSENGER
SELECT
	Survived,
	COUNT(Survived) AS Total
FROM TITANIC_DATASET
GROUP BY Survived


-- TOTAL NUMBER OF SURVIVED MALE AND FEMALE

SELECT
	Sex,
	COUNT(Survived) AS Total_survived
FROM TITANIC_DATASET
GROUP BY Sex, Survived
HAVING Survived = 1


-- TOTAL NUMBER OF UNSURVIVED MALE AND FEMALE

SELECT
	Sex,
	COUNT(Survived) Unsurvived
FROM TITANIC_DATASET
GROUP BY Sex, Survived
HAVING Survived = 0;


-- TOTAL NUMBER OF PCLASS 

SELECT
	Pclass,
	COUNT(Pclass) Total
FROM TITANIC_DATASET
GROUP BY Pclass
Order by Pclass ASC;


-- TOTAL NUMBER OF SURVIVED AGE

SELECT
	Age,
	COUNT(Survived) Total_Survived
FROM TITANIC_DATASET
GROUP BY Age, Survived
HAVING Survived = 1;


-- TOTAL NUMBER OF PCLASS BY SEX

SELECT
	Sex,
	Pclass,
	COUNT(Pclass) AS Total_Pclass
FROM TITANIC_DATASET
GROUP BY Sex, Pclass
ORDER BY Pclass ASC;


-- TOTAL NUMBER OF SURVIVED BY PCLASS

SELECT
	Pclass,
	COUNT(Pclass) Surv_Pclass
FROM TITANIC_DATASET
GROUP BY Survived, Pclass
HAVING Survived = 1
ORDER BY Pclass ASC;


-- TOTAL PASSENGER WITH SibSp

SELECT
	COUNT(SibSp) AS PASS_SIBSP
FROM TITANIC_DATASET
WHERE SibSp>0


-- MALE AND FEMALE WITH SibSp

SELECT
	Sex,
	COUNT(SibSp) Sex_With_SibSp
FROM TITANIC_DATASET
WHERE SibSp>0
GROUP BY Sex


-- TOTAL SUM OF SibSp

SELECT
	SUM(SibSp) Sum_SibSp
FROM TITANIC_DATASET


-- TOTAL PASSENGER WITH PARCH

SELECT
	COUNT(Parch) Total_Parch
FROM TITANIC_DATASET
WHERE Parch>0;


-- TOTAL NUMBER MALE AND FEMALE WITH PARCH

SELECT
	Sex,
	COUNT(Parch) Sex_with_Parch
FROM TITANIC_DATASET
WHERE Parch>0
GROUP BY Sex;


-- TOTAL SUM OF PARCH BY SEX

SELECT
	Sex,
	SUM(Parch) Sum_Parch
FROM TITANIC_DATASET
GROUP BY Sex;


-- TOTAL NUMBER OF SURVIVED PASSENGER AGE<=10

SELECT
	COUNT(Survived) '<=10 Survived'
FROM TITANIC_DATASET
WHERE Age<=10



-- TOTAL NUMBER OF SURVIVED PASSENGER AGE>50

SELECT
	COUNT(Survived) '>50 Survived'
FROM TITANIC_DATASET
WHERE Age>50


-- AVERAGE VALUE OF FARE

SELECT
	AVG(Fare) Avg_fare
FROM TITANIC_DATASET

-- MIN FARE

SELECT
	MIN(Fare) Min_fare
FROM TITANIC_DATASET

-- MAX FARE

SELECT
	MAX(Fare) Max_fare
FROM TITANIC_DATASET


-- TOTAL SUM OF FARE

SELECT
	SUM(Fare) Sum_fare
FROM TITANIC_DATASET


-- TOTAL SUM OF FARE BY SEX

SELECT
	Sex,
	SUM(Fare) Sum_fare
FROM TITANIC_DATASET
GROUP BY Sex;


-- PERCENTAGE OF SURVIVED AND UNSURVIVED PASSENGER

SELECT
	((SELECT COUNT(Survived) FROM TITANIC_DATASET WHERE Survived>0)*100.0/COUNT(Survived)) Survived_per,
	((SELECT COUNT(Survived) FROM TITANIC_DATASET WHERE Survived=0)*100.0/COUNT(Survived)) Unsurvived_per
FROM TITANIC_DATASET


-- TOTAL NUMBER OF EMBARKED

SELECT
	Embarked,
	COUNT(Embarked) Total_Embarked
FROM TITANIC_DATASET
GROUP BY Embarked;
